# ###
# GET http://localhost:3333/notification/?voce=bixao

# Na prática a gente não passa direto a request

# A gente trata a request e faz o que foi pedido

# Por exemplo

# Vamos receber nessa rota, um body que vai ter:

# {
#     "n1": 3,
#     "n2": 4
# }

# ai agora, usa o que tu sabe para receber esses valores e devolver na response o JSON 

# {
#     "result": 7
# }

# (obs: faça o calculo e armazene uma variavel)

# Use a lógica de programação normal mesmo em conjuntos com esses dados dinâmicos que estamos recebendo na request


###
POST http://localhost:3333/notification
Content-Type: application/json

{
  "n1": 3,
  "n2": 4
}