
@server_port = {{$dotenv SERVER_PORT}}

###
POST http://localhost:{{server_port}}/company/validate
Content-Type: application/json

{
    "email": "nicthur.s@gmail.com",
    "password": "18052004"
}

###
DELETE http://localhost:{{server_port}}/company
Authorization: Bearded eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MzI0OWI3NzJmZjFmNzY4NTJhZWZkOCIsImlhdCI6MTczMTQ0MDIxMCwiZXhwIjoxNzMxNDQzODEwfQ.OOzRa6TQu8gUGvCSpeuqU1_MtHj8_sjAEmug__fMqLY
